/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionComponent: typeof import('./src/components/AccordionComponent.vue')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Calendar: typeof import('primevue/calendar')['default']
    EditorComponent: typeof import('./src/components/EditorComponent.vue')['default']
  }
}
